apiVersion: v1
kind: ConfigMap
metadata:
  name: script-exporter-configmap
data:
  script-exporter.yml: |
    scripts:
      - name: audit-write-time
        script: |
          #!/bin/bash
          if (( $(($(date +%s) - $(stat -c %Y /var/log/audit/audit.log))) < 86400 )); then
            exit 0
          else
             exit 1
          fi